{
 "title": "Model Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Inference Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(inference_time_seconds_bucket[5m]) / rate(inference_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Prediction Distribution (15 m)",
   "type": "heatmap",
   "description": "Average per second count of predictions which shows which playlists are being recommended the most",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (output_label) (rate(infernce_ouput_total[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inferences Done",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inference_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Time Quartiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}