apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotifybuddies-fastapi
  namespace: spotifybuddies-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotifybuddies-fastapi
  template:
    metadata:
      labels:
        app: spotifybuddies-fastapi
    spec:
      containers:
        - name: fastapi
          image: us-central1-docker.pkg.dev/spotifybuddies-464323/spotifybuddies-docker-repo/fastapi:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: REDIS_URL
              value: redis://spotifybuddies-redis.spotifybuddies-monitoring.svc.cluster.local:6379/0
