{
 "title": "API Request Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "HTTP Success Rate (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"/api/playlist/recommend/\", status != \"5xx\"}[15m])) / sum(rate(http_requests_total{handler=\"/api/playlist/recommend/\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playlist Recommendation average request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/api/playlist/recommend/\", job=\"playlist_recommendation\"}[1m]) / \r\nrate(http_request_duration_seconds_count{handler=\"/api/playlist/recommend/\", job=\"playlist_recommendation\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Playlist Recommendation request duration percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/api/playlist/recommend/\"}[1m]))",
     "legendFormat": "{{Median}}"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/api/playlist/recommend/\"}[1m]))",
     "legendFormat": "{{95th percentile}}"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/api/playlist/recommend/\"}[1m]))",
     "legendFormat": "{{99th percentile}}"
    }
   ]
  },
  {
   "title": "Failed request per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/api/playlist/recommend/\", status=\"4xx\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/api/playlist/recommend/\", status=\"5xx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/api/playlist/recommend/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}