{
 "title": "Model Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Model Prediction Distribution (15 m)",
   "type": "heatmap",
   "description": "Average per second count of predictions which shows which playlists are being recommended the most",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "inference_diversity_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Time Quartiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inference_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Inferences Done",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    { "expr": "inference_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cold User ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    { "expr": "cold_user_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraction of cold users encountered per 30 m",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cold_user_total[30m]) / rate(inference_requests_total[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Inference Time (30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "1000 * rate(inference_time_seconds_sum[30m]) / rate(inference_time_seconds_count[30m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}